// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knjmjwpatmexwtlesqxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtuam1qd3BhdG1leHd0bGVzcXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTcyNzAsImV4cCI6MjA2NDYzMzI3MH0.tDmvA70p1QP1IZUCGAffONsgsw_iJQ7vSkzjAeWHWpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);